// Copyright (c) 2026-present Maciej Szymczak and contributors
// SPDX-License-Identifier: AGPL-3.0-only

// Generated by scripts/generate-release-notes.mjs from docs/releases/.
// Do not edit; run `pnpm generate:release-notes`.

export type TBuildIdentity = {
  version: string;
  highlights: string[];
  upstream: { version: string; revision: string };
};

export const RELEASE_NOTES: TBuildIdentity = {
  version: "0.1.0-rc.44",
  highlights: [
    "A copied work item never carries another member's private work, and only an administrator can start one.",
    "Assignees who are not members of the copy are dropped, and the number is reported.",
    "Relations are copied only where both ends are inside the copy.",
    "Images inside a copied work item are copied too, and authorised against the person who asked for the copy.",
    "A copy that is interrupted resumes rather than duplicating.",
  ],
  upstream: {
    version: "1.4.0",
    revision: "917b23a6",
  },
};
