// Copyright (c) 2026-present Maciej Szymczak and contributors
// SPDX-License-Identifier: AGPL-3.0-only

// Generated by scripts/generate-release-notes.mjs from docs/releases/.
// Do not edit; run `pnpm generate:release-notes`.

export type TBuildIdentity = {
  version: string;
  highlights: string[];
  upstream: { version: string; revision: string };
};

export const RELEASE_NOTES: TBuildIdentity = {
  version: "0.1.0-rc.56",
  highlights: [
    "Encrypted notification email is delivered instead of being held indefinitely.",
    "The community deployment can reach its own mail settings.",
    "Notification settings say when an unverified key is silencing email.",
    "Project invitations can be created again.",
  ],
  upstream: {
    version: "1.4.0",
    revision: "917b23a6",
  },
};
