// Copyright (c) 2026-present Maciej Szymczak and contributors
// SPDX-License-Identifier: AGPL-3.0-only

// Generated by scripts/generate-release-notes.mjs from docs/releases/.
// Do not edit; run `pnpm generate:release-notes`.

export type TBuildIdentity = {
  version: string;
  highlights: string[];
  upstream: { version: string; revision: string };
};

export const RELEASE_NOTES: TBuildIdentity = {
  version: "0.1.0-rc.57",
  highlights: [
    "Activity notifications are no longer discarded in silence.",
    "A notification that cannot be built now gives up and says why.",
    "A trainer whose calendar cannot be read is no longer offered or booked.",
    "Encrypted notifications can describe themselves in the Subject, if an operator asks.",
  ],
  upstream: {
    version: "1.4.0",
    revision: "917b23a6",
  },
};
