# Copyright (c) 2026-present Maciej Szymczak and contributors
# SPDX-License-Identifier: AGPL-3.0-only
# See the LICENSE file for details.

# Generated by Django 4.2.30 on 2026-07-11 16:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0121_alter_estimate_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ext", "0002_issue_properties"),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueWorkLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('duration', models.PositiveIntegerField(help_text='Logged time in minutes', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1440)])),
                ('description', models.TextField(blank=True, max_length=5000)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worklogs', to='db.issue')),
                ('logged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worklogs', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Issue Work Log',
                'verbose_name_plural': 'Issue Work Logs',
                'db_table': 'ext_issue_worklogs',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['issue'], name='ext_issue_w_issue_i_1e972b_idx'), models.Index(fields=['project', 'logged_by'], name='ext_issue_w_project_867fac_idx'), models.Index(fields=['workspace', 'created_at'], name='ext_issue_w_workspa_268981_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name="issueworklog",
            constraint=models.CheckConstraint(
                check=models.Q(("duration__gte", 1), ("duration__lte", 1440)),
                name="ext_issue_worklog_duration_range",
            ),
        ),
    ]
