# Copyright (c) 2026-present Maciej Szymczak and contributors
# SPDX-License-Identifier: AGPL-3.0-only
# See the LICENSE file for details.
#
# Generated by Django 5.2.16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ext', '0011_import_job_preview_nonce'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstanceAdminWebAuthnChallenge',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('purpose', models.CharField(choices=[('registration', 'Registration'), ('authentication', 'Authentication')], max_length=16)),
                ('challenge', models.CharField(db_index=True, max_length=128)),
                ('session_key', models.CharField(db_index=True, max_length=128)),
                ('rp_id', models.CharField(max_length=255)),
                ('origin', models.CharField(max_length=255)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_webauthn_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Instance Admin WebAuthn Challenge',
                'db_table': 'ext_instance_admin_webauthn_challenges',
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(fields=('challenge',), name='uniq_admin_webauthn_challenge')],
            },
        ),
        migrations.CreateModel(
            name='InstanceAdminWebAuthnCredential',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('credential_id', models.CharField(db_index=True, max_length=1400)),
                ('public_key', models.TextField()),
                ('sign_count', models.PositiveBigIntegerField(default=0)),
                ('transports', models.JSONField(blank=True, default=list)),
                ('aaguid', models.CharField(blank=True, default='', max_length=36)),
                ('user_handle', models.CharField(max_length=64)),
                ('nickname', models.CharField(max_length=64)),
                ('backup_eligible', models.BooleanField(default=False)),
                ('backup_state', models.BooleanField(default=False)),
                ('last_uv', models.BooleanField(default=False)),
                ('last_used_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_used_ip', models.CharField(blank=True, default='', max_length=45)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_webauthn_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Instance Admin WebAuthn Credential',
                'db_table': 'ext_instance_admin_webauthn_credentials',
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('credential_id',), name='uniq_admin_webauthn_credential_id'), models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('user', 'nickname'), name='uniq_admin_webauthn_nickname_per_user')],
            },
        ),
    ]
