# Generated by Django 5.2.16 on 2026-09-02

import django.core.validators
import django.db.models.deletion
import plane.ext.models.capacity
import uuid
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ("db", "0131_google_calendar_workshop_type"),
        ("ext", "0016_workspace_home_defaults"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GoogleCalendarCredential",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ("google_subject", models.CharField(max_length=255)),
                ("encrypted_refresh_token", models.TextField()),
                ("encryption_key_id", models.CharField(max_length=64)),
                ("granted_scopes", models.JSONField(default=list)),
                ("status", models.CharField(choices=[("connected", "Connected"), ("reauthorization_required", "Reauthorization required")], default="connected", max_length=32)),
                ("last_successful_at", models.DateTimeField(blank=True, null=True)),
                ("last_error_code", models.CharField(blank=True, max_length=64)),
                ("created_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created_by", to=settings.AUTH_USER_MODEL, verbose_name="Created By")),
                ("updated_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_updated_by", to=settings.AUTH_USER_MODEL, verbose_name="Last Modified By")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="google_calendar_credentials", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "ext_google_calendar_credentials",
                "constraints": [models.UniqueConstraint(condition=models.Q(deleted_at__isnull=True), fields=("user", "google_subject"), name="ext_gcal_credential_unique_subject")],
            },
        ),
        migrations.CreateModel(
            name="TrainerProfile",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ("status", models.CharField(choices=[("active", "Active"), ("suspended", "Suspended")], default="active", max_length=16)),
                ("timezone", models.CharField(default="UTC", max_length=255)),
                ("weekly_schedule", models.JSONField(default=plane.ext.models.capacity.empty_week)),
                ("created_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created_by", to=settings.AUTH_USER_MODEL, verbose_name="Created By")),
                ("updated_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_updated_by", to=settings.AUTH_USER_MODEL, verbose_name="Last Modified By")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="trainer_profiles", to=settings.AUTH_USER_MODEL)),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="trainer_profiles", to="db.workspace")),
            ],
            options={
                "db_table": "ext_trainer_profiles",
                "indexes": [models.Index(fields=["workspace", "status"], name="ext_trainer_ws_status_idx")],
                "constraints": [models.UniqueConstraint(condition=models.Q(deleted_at__isnull=True), fields=("workspace", "user"), name="ext_trainer_unique_workspace_user")],
            },
        ),
        migrations.CreateModel(
            name="TrainerCalendarSelection",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ("encrypted_calendar_ids", models.JSONField(default=list)),
                ("calendar_id_hashes", models.JSONField(default=list)),
                ("revision", models.PositiveBigIntegerField(default=1)),
                ("created_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created_by", to=settings.AUTH_USER_MODEL, verbose_name="Created By")),
                ("updated_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_updated_by", to=settings.AUTH_USER_MODEL, verbose_name="Last Modified By")),
                ("credential", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="trainer_selections", to="ext.googlecalendarcredential")),
                ("trainer", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="calendar_selection", to="ext.trainerprofile")),
            ],
            options={"db_table": "ext_trainer_calendar_selections"},
        ),
        migrations.CreateModel(
            name="TrainerScheduleException",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ("local_date", models.DateField()),
                ("mode", models.CharField(choices=[("unavailable", "Unavailable"), ("override", "Override")], max_length=16)),
                ("intervals", models.JSONField(blank=True, default=list)),
                ("created_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created_by", to=settings.AUTH_USER_MODEL, verbose_name="Created By")),
                ("updated_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_updated_by", to=settings.AUTH_USER_MODEL, verbose_name="Last Modified By")),
                ("trainer", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="schedule_exceptions", to="ext.trainerprofile")),
            ],
            options={
                "db_table": "ext_trainer_schedule_exceptions",
                "indexes": [models.Index(fields=["trainer", "local_date"], name="ext_trainer_exc_date_idx")],
                "constraints": [models.UniqueConstraint(condition=models.Q(deleted_at__isnull=True), fields=("trainer", "local_date"), name="ext_trainer_exception_unique_date")],
            },
        ),
        migrations.CreateModel(
            name="WorkshopSchedule",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                ("preparation_minutes", models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1440)])),
                ("travel_before_minutes", models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1440)])),
                ("travel_after_minutes", models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1440)])),
                ("created_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created_by", to=settings.AUTH_USER_MODEL, verbose_name="Created By")),
                ("updated_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_updated_by", to=settings.AUTH_USER_MODEL, verbose_name="Last Modified By")),
                ("issue", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="workshop_schedule", to="db.issue")),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="workshop_schedules", to="db.project")),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="workshop_schedules", to="db.workspace")),
            ],
            options={
                "db_table": "ext_workshop_schedules",
                "indexes": [models.Index(fields=["workspace", "starts_at", "ends_at"], name="ext_workshop_ws_range_idx"), models.Index(fields=["project", "starts_at"], name="ext_workshop_proj_start_idx")],
                "constraints": [models.CheckConstraint(condition=models.Q(ends_at__gt=models.F("starts_at")), name="ext_workshop_valid_range")],
            },
        ),
    ]
