# Copyright (c) 2026-present Maciej Szymczak and contributors
# SPDX-License-Identifier: AGPL-3.0-only
# See the LICENSE file for details.

# Generated by Django 5.2.16 on 2026-09-02 14:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0131_google_calendar_workshop_type'),
        ('ext', '0019_trainer_schedule_revision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCopyJob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('completed_with_errors', 'Completed with errors'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=32)),
                ('stage', models.CharField(choices=[('issues', 'Work items'), ('parents', 'Sub-item links'), ('satellites', 'Labels, assignees and membership'), ('properties', 'Custom property values'), ('relations', 'Relations'), ('assets', 'Description images')], default='issues', max_length=32)),
                ('plan', models.JSONField(default=dict)),
                ('remap', models.JSONField(default=dict)),
                ('total', models.PositiveIntegerField(default=0)),
                ('copied', models.PositiveIntegerField(default=0)),
                ('counts', models.JSONField(default=dict)),
                ('skipped', models.JSONField(default=list)),
                ('errors', models.JSONField(default=list)),
                ('reason', models.CharField(blank=True, max_length=64)),
                ('cursor', models.BigIntegerField(default=0)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('lease_token', models.UUIDField(blank=True, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_copy_jobs', to=settings.AUTH_USER_MODEL)),
                ('source_project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copy_jobs_as_source', to='db.project')),
                ('target_project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='copy_job', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_copy_jobs', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Project copy job',
                'db_table': 'ext_project_copy_jobs',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['workspace', 'status'], name='ext_project_workspa_93c65d_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('status', 'processing'), _negated=True), models.Q(('lease_token__isnull', False), ('started_at__isnull', False)), _connector='OR'), name='ext_project_copy_job_processing_holds_lease'), models.CheckConstraint(condition=models.Q(models.Q(('status__in', ('completed', 'completed_with_errors', 'failed', 'cancelled')), _negated=True), models.Q(('completed_at__isnull', False), ('lease_token__isnull', True)), _connector='OR'), name='ext_project_copy_job_terminal_released')],
            },
        ),
    ]
