# Copyright (c) 2026-present Maciej Szymczak and contributors
# SPDX-License-Identifier: AGPL-3.0-only
# See the LICENSE file for details.

# Generated by Django 5.2.16 on 2026-09-13 19:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ext", "0027_planner_booking_operations"),
    ]

    operations = [
        migrations.AddField(
            model_name="googlecalendarcredential",
            name="primary_calendar_timezone",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="googlecalendarcredential",
            name="timezone_checked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
