# Copyright (c) 2026-present Maciej Szymczak and contributors
# SPDX-License-Identifier: AGPL-3.0-only
# See the LICENSE file for details.

# Generated by Django 5.2.16 on 2026-09-18 05:07

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0133_email_outbox_outer_subject'),
        ('ext', '0029_google_training_rules'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacityauditevent',
            name='action',
            field=models.CharField(choices=[('trainer.activated', 'Trainer activated'), ('trainer.suspended', 'Trainer suspended'), ('schedule.updated', 'Schedule updated'), ('google.connected', 'Google connected'), ('google.calendars_updated', 'Calendars updated'), ('google.disconnected', 'Google disconnected'), ('workshop.updated', 'Workshop updated'), ('workshop.removed', 'Workshop removed'), ('plan_draft.created', 'Plan draft created'), ('plan_draft.updated', 'Plan draft updated'), ('plan_draft.removed', 'Plan draft removed'), ('plan_hold.created', 'Plan hold created'), ('plan_hold.released', 'Plan hold released'), ('plan.scheduled', 'Plan scheduled'), ('checklist_template.updated', 'Checklist template updated'), ('checklist_template.removed', 'Checklist template removed'), ('checklist.applied', 'Checklist applied')], max_length=64),
        ),
        migrations.CreateModel(
            name='WorkshopChecklistTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('is_default', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop_checklist_templates', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Workshop checklist template',
                'db_table': 'ext_workshop_checklist_templates',
                'ordering': ('name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='WorkshopChecklistItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('position', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('assignee_mode', models.CharField(choices=[('unassigned', 'Unassigned'), ('fixed', 'A specific person'), ('workshop_trainer', "The workshop's trainer")], default='unassigned', max_length=20)),
                ('offset_days', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-365), django.core.validators.MaxValueValidator(365)])),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workshop_checklist_items', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ext.workshopchecklisttemplate')),
            ],
            options={
                'verbose_name': 'Workshop checklist item',
                'db_table': 'ext_workshop_checklist_items',
                'ordering': ('position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='WorkshopChecklistOrigin',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('offset_days', models.IntegerField(validators=[django.core.validators.MinValueValidator(-365), django.core.validators.MaxValueValidator(365)])),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('issue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_origin', to='db.issue')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_issues', to='ext.workshopchecklistitem')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop_checklist_origins', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Workshop checklist origin',
                'db_table': 'ext_workshop_checklist_origins',
                'indexes': [models.Index(fields=['workspace'], name='ext_wco_ws_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='workshopchecklisttemplate',
            index=models.Index(fields=['workspace', 'is_default'], name='ext_wct_ws_default_idx'),
        ),
        migrations.AddConstraint(
            model_name='workshopchecklisttemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('workspace', 'name'), name='ext_workshop_checklist_template_unique_name'),
        ),
        migrations.AddConstraint(
            model_name='workshopchecklistitem',
            constraint=models.UniqueConstraint(fields=('template', 'position'), name='ext_workshop_checklist_item_position'),
        ),
        migrations.AddConstraint(
            model_name='workshopchecklistitem',
            constraint=models.CheckConstraint(condition=models.Q(('offset_days__gte', -365), ('offset_days__lte', 365)), name='ext_workshop_checklist_item_offset_range'),
        ),
        migrations.AddConstraint(
            model_name='workshopchecklistitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('assignee_mode', 'fixed'), _negated=True), ('assignee__isnull', False), _connector='OR'), name='ext_workshop_checklist_item_fixed_needs_assignee'),
        ),
    ]
