# Copyright (c) 2026-present Maciej Szymczak and contributors
# SPDX-License-Identifier: AGPL-3.0-only
# See the LICENSE file for details.

# Generated by Django 5.2.16 on 2026-09-18 15:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0133_email_outbox_outer_subject'),
        ('ext', '0029_google_training_rules'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerTrainingSyncState',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('consent_state', models.CharField(choices=[('ok', 'Ok'), ('consent_missing', 'Consent missing'), ('reauth_required', 'Reauthorization required'), ('not_connected', 'Not connected'), ('access_lost', 'Access lost')], default='not_connected', max_length=32)),
                ('last_materialized_at', models.DateTimeField(blank=True, null=True)),
                ('last_probed_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, max_length=64)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('trainer_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='training_sync_state', to='ext.trainerprofile')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Trainer training sync state',
                'db_table': 'ext_trainer_training_sync_states',
            },
        ),
        migrations.CreateModel(
            name='TrainingCalendarSyncState',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('window_starts_at', models.DateTimeField()),
                ('window_ends_at', models.DateTimeField()),
                ('last_incremental_at', models.DateTimeField(blank=True, null=True)),
                ('last_full_scan_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, max_length=64)),
                ('failure_count', models.PositiveSmallIntegerField(default=0)),
                ('available_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lease_token', models.UUIDField(blank=True, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('rule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sync_state', to='ext.googletrainingrule')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_sync_states', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Training calendar sync state',
                'db_table': 'ext_training_calendar_sync_states',
                'indexes': [models.Index(fields=['available_at'], name='ext_train_sync_ready_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrainingEventOccurrence',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('event_key', models.CharField(max_length=64)),
                ('rule_label', models.CharField(blank=True, max_length=100)),
                ('calendar_id_hash', models.CharField(max_length=64)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('pending', 'Pending')], max_length=16)),
                ('state', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('disappeared', 'Disappeared')], default='active', max_length=16)),
                ('encrypted_summary', models.TextField(blank=True)),
                ('encryption_key_id', models.CharField(blank=True, max_length=64)),
                ('first_seen_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occurrences', to='ext.googletrainingrule')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_event_occurrences', to=settings.AUTH_USER_MODEL)),
                ('trainer_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_event_occurrences', to='ext.trainerprofile')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_event_occurrences', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Training event occurrence',
                'db_table': 'ext_training_event_occurrences',
                'ordering': ('starts_at', 'id'),
                'indexes': [models.Index(fields=['workspace', 'starts_at', 'ends_at'], name='ext_train_occ_ws_range_idx'), models.Index(fields=['trainer', 'starts_at'], name='ext_train_occ_trainer_idx'), models.Index(fields=['workspace', 'state', 'starts_at'], name='ext_train_occ_state_idx')],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'trainer', 'event_key'), name='ext_training_occurrence_unique'), models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='ext_training_occurrence_range')],
            },
        ),
    ]
