# Copyright (c) 2026-present Maciej Szymczak and contributors
# SPDX-License-Identifier: AGPL-3.0-only
# See the LICENSE file for details.

# Generated by Django 5.2.16 on 2026-09-18 05:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0133_email_outbox_outer_subject'),
        ('ext', '0030_workshop_checklist_templates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopRoleMember',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'Workshop role member',
                'db_table': 'ext_workshop_role_members',
                'ordering': ('id',),
            },
        ),
        migrations.AlterField(
            model_name='capacityauditevent',
            name='action',
            field=models.CharField(choices=[('trainer.activated', 'Trainer activated'), ('trainer.suspended', 'Trainer suspended'), ('schedule.updated', 'Schedule updated'), ('google.connected', 'Google connected'), ('google.calendars_updated', 'Calendars updated'), ('google.disconnected', 'Google disconnected'), ('workshop.updated', 'Workshop updated'), ('workshop.removed', 'Workshop removed'), ('plan_draft.created', 'Plan draft created'), ('plan_draft.updated', 'Plan draft updated'), ('plan_draft.removed', 'Plan draft removed'), ('plan_hold.created', 'Plan hold created'), ('plan_hold.released', 'Plan hold released'), ('plan.scheduled', 'Plan scheduled'), ('checklist_template.updated', 'Checklist template updated'), ('checklist_template.removed', 'Checklist template removed'), ('checklist.applied', 'Checklist applied'), ('workshop_role.updated', 'Workshop role updated'), ('workshop_role.removed', 'Workshop role removed')], max_length=64),
        ),
        migrations.AlterField(
            model_name='workshopchecklistitem',
            name='assignee_mode',
            field=models.CharField(choices=[('unassigned', 'Unassigned'), ('fixed', 'A specific person'), ('workshop_trainer', "The workshop's trainer"), ('role', 'Whoever holds a role')], default='unassigned', max_length=20),
        ),
        migrations.CreateModel(
            name='WorkshopRole',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop_roles', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Workshop role',
                'db_table': 'ext_workshop_roles',
                'ordering': ('name', 'id'),
            },
        ),
        migrations.AddField(
            model_name='workshopchecklistitem',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_items', to='ext.workshoprole'),
        ),
        migrations.AddConstraint(
            model_name='workshopchecklistitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('assignee_mode', 'role'), _negated=True), ('role__isnull', False), _connector='OR'), name='ext_workshop_checklist_item_role_needs_role'),
        ),
        migrations.AddField(
            model_name='workshoprolemember',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='workshoprolemember',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop_role_seats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workshoprolemember',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='ext.workshoprole'),
        ),
        migrations.AddField(
            model_name='workshoprolemember',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='workshoprole',
            name='members',
            field=models.ManyToManyField(related_name='workshop_roles', through='ext.WorkshopRoleMember', through_fields=('role', 'member'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='workshoprolemember',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('role', 'member'), name='ext_workshop_role_member_unique'),
        ),
        migrations.AddConstraint(
            model_name='workshoprole',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('workspace', 'name'), name='ext_workshop_role_unique_name'),
        ),
    ]
