# Copyright (c) 2026-present Maciej Szymczak and contributors
# SPDX-License-Identifier: AGPL-3.0-only
# See the LICENSE file for details.

# Generated by Django 5.2.16 on 2026-09-18 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0133_email_outbox_outer_subject'),
        ('ext', '0030_training_event_materialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingeventoccurrence',
            name='imported_issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_training_occurrences', to='db.issue'),
        ),
    ]
