# Copyright (c) 2026-present Maciej Szymczak and contributors
# SPDX-License-Identifier: AGPL-3.0-only
# See the LICENSE file for details.

# Generated by Django 5.2.16 on 2026-09-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ext', '0033_training_import_marker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googletrainingrule',
            name='encrypted_organizer',
            field=models.TextField(blank=True, default=''),
        ),
    ]
