# Copyright (c) 2026-present Maciej Szymczak and contributors
# SPDX-License-Identifier: AGPL-3.0-only
# See the LICENSE file for details.

# Generated by Django 5.2.16 on 2026-09-20 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ext', '0034_training_rule_organizer_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='googletrainingrule',
            name='writer_credential',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='written_training_rules', to='ext.googlecalendarcredential'),
        ),
        migrations.AlterField(
            model_name='capacityauditevent',
            name='action',
            field=models.CharField(choices=[('trainer.activated', 'Trainer activated'), ('trainer.suspended', 'Trainer suspended'), ('schedule.updated', 'Schedule updated'), ('google.connected', 'Google connected'), ('google.calendars_updated', 'Calendars updated'), ('google.disconnected', 'Google disconnected'), ('workshop.updated', 'Workshop updated'), ('workshop.removed', 'Workshop removed'), ('plan_draft.created', 'Plan draft created'), ('plan_draft.updated', 'Plan draft updated'), ('plan_draft.removed', 'Plan draft removed'), ('plan_hold.created', 'Plan hold created'), ('plan_hold.released', 'Plan hold released'), ('plan.scheduled', 'Plan scheduled'), ('checklist_template.updated', 'Checklist template updated'), ('checklist_template.removed', 'Checklist template removed'), ('checklist.applied', 'Checklist applied'), ('workshop_role.updated', 'Workshop role updated'), ('workshop_role.removed', 'Workshop role removed'), ('calendar_writer.connected', 'Calendar writer connected'), ('calendar_writer.removed', 'Calendar writer removed')], max_length=64),
        ),
    ]
