# Copyright (c) 2026-present Maciej Szymczak and contributors
# SPDX-License-Identifier: AGPL-3.0-only
# See the LICENSE file for details.

# Generated by Django 5.2.16 on 2026-09-20 14:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0133_email_outbox_outer_subject'),
        ('ext', '0035_training_rule_writer_credential'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopSessionCalendarEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('source_session_id', models.UUIDField(db_index=True)),
                ('source_issue_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('credential_subject', models.CharField(blank=True, default='', max_length=255)),
                ('google_event_id', models.CharField(blank=True, default='', max_length=128)),
                ('google_ical_uid', models.CharField(blank=True, default='', max_length=255)),
                ('intent', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], default='present', max_length=16)),
                ('desired_starts_at', models.DateTimeField(blank=True, null=True)),
                ('desired_ends_at', models.DateTimeField(blank=True, null=True)),
                ('desired_fingerprint', models.CharField(blank=True, default='', max_length=64)),
                ('revision', models.PositiveBigIntegerField(default=1)),
                ('synced_revision', models.PositiveBigIntegerField(default=0)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('failed', 'Failed'), ('blocked_no_writer', 'Blocked: no writing account'), ('blocked', 'Blocked')], default='pending', max_length=24)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('available_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lease_token', models.UUIDField(blank=True, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, default='', max_length=64)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('credential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ext.googlecalendarcredential')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ext.googletrainingrule')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ext.workshopsession')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.workspace')),
            ],
            options={
                'db_table': 'ext_workshop_session_calendar_events',
                'indexes': [models.Index(fields=['state', 'available_at'], name='ext_worksho_state_7b2d58_idx'), models.Index(fields=['workspace', 'state'], name='ext_worksho_workspa_03fb95_idx')],
                'constraints': [models.UniqueConstraint(fields=('trainer', 'source_session_id'), name='ext_workshop_calendar_event_unique'), models.CheckConstraint(condition=models.Q(('attempts__lte', 100)), name='ext_workshop_calendar_event_attempts'), models.CheckConstraint(condition=models.Q(('intent', 'absent'), models.Q(('desired_ends_at__isnull', False), ('desired_starts_at__isnull', False)), _connector='OR'), name='ext_workshop_calendar_event_window')],
            },
        ),
    ]
