# Copyright (c) 2026-present Maciej Szymczak and contributors
# SPDX-License-Identifier: AGPL-3.0-only
# See the LICENSE file for details.

# Generated by Django 5.2.16 on 2026-09-21 16:06

from django.db import migrations, models
from django.utils import timezone


def retire_unused_workshop_links(apps, schema_editor):
    """Keep Workshops where they are used; withdraw them where they are not.

    Until this release the Workshop type was added to every project as soon as
    anybody in the workspace became a trainer, so most projects that offer it
    never asked for it. A project that already holds a Workshop is treated as
    having chosen to -- nobody loses a workshop, and nobody's project suddenly
    refuses a type it is using. Every other project stops offering it, and can
    turn it back on from its own settings.

    Soft-deleted by setting `deleted_at`, the way the application removes this
    link, so the uniqueness condition on live links still lets a project re-enable
    Workshops afterwards.
    """
    ProjectIssueType = apps.get_model("db", "ProjectIssueType")
    Issue = apps.get_model("db", "Issue")
    now = timezone.now()
    links = ProjectIssueType.objects.filter(issue_type__system_key="workshop", deleted_at__isnull=True)
    for link in links.iterator():
        in_use = Issue.objects.filter(
            project_id=link.project_id, type_id=link.issue_type_id, deleted_at__isnull=True
        ).exists()
        if not in_use:
            ProjectIssueType.objects.filter(pk=link.pk).update(deleted_at=now)


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0133_email_outbox_outer_subject'),
        ('ext', '0036_workshop_calendar_outbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacityauditevent',
            name='action',
            field=models.CharField(choices=[('trainer.activated', 'Trainer activated'), ('trainer.suspended', 'Trainer suspended'), ('schedule.updated', 'Schedule updated'), ('google.connected', 'Google connected'), ('google.calendars_updated', 'Calendars updated'), ('google.disconnected', 'Google disconnected'), ('workshop.updated', 'Workshop updated'), ('workshop.removed', 'Workshop removed'), ('plan_draft.created', 'Plan draft created'), ('plan_draft.updated', 'Plan draft updated'), ('plan_draft.removed', 'Plan draft removed'), ('plan_hold.created', 'Plan hold created'), ('plan_hold.released', 'Plan hold released'), ('plan.scheduled', 'Plan scheduled'), ('checklist_template.updated', 'Checklist template updated'), ('checklist_template.removed', 'Checklist template removed'), ('checklist.applied', 'Checklist applied'), ('workshop_role.updated', 'Workshop role updated'), ('workshop_role.removed', 'Workshop role removed'), ('calendar_writer.connected', 'Calendar writer connected'), ('calendar_writer.removed', 'Calendar writer removed'), ('workshops.enabled', 'Workshops enabled in a project'), ('workshops.disabled', 'Workshops disabled in a project')], max_length=64),
        ),
        # Irreversible in effect rather than in form: downgrading leaves these
        # projects without the type, and the older build re-adds it to every
        # project on its own the next time it provisions system types.
        migrations.RunPython(retire_unused_workshop_links, migrations.RunPython.noop),
    ]
