# Copyright (c) 2026-present Maciej Szymczak and contributors
# SPDX-License-Identifier: AGPL-3.0-only
# See the LICENSE file for details.

# Generated by Django 5.2.16 on 2026-09-23 07:57

from django.conf import settings
from django.db import migrations, models

# Kept beside the service's own list rather than imported from it: a migration
# has to keep describing the world as it was on the day it ran, and the service
# is free to grow another role tomorrow.
ROLES = (
    ("workshop_sales", "Sales", "Who sold this training.", False, 1000),
    ("workshop_pm", "PM", "Who runs this training as a project.", False, 2000),
    (
        "workshop_trainer",
        "Trainers",
        "Who delivers this training. Sessions start from this list.",
        True,
        3000,
    ),
)


def provision_workshop_role_properties(apps, schema_editor):
    """Give the Workshop types that already exist their three role properties.

    Without this the roles would appear only in workspaces that enable Workshops
    after this release, and every workshop already in Hangar would have nowhere
    to record who sold, ran or delivered it.
    """
    IssueType = apps.get_model("db", "IssueType")
    IssueProperty = apps.get_model("ext", "IssueProperty")

    for issue_type in IssueType.objects.filter(system_key="workshop", deleted_at__isnull=True).iterator():
        taken = set(
            IssueProperty.objects.filter(issue_type=issue_type, deleted_at__isnull=True).values_list(
                "display_name", flat=True
            )
        )
        for system_key, display_name, description, is_multi, sort_order in ROLES:
            if IssueProperty.objects.filter(
                issue_type=issue_type, system_key=system_key, deleted_at__isnull=True
            ).exists():
                continue
            # A workspace may already have added its own column under this name,
            # and the name is unique per type. Theirs keeps it.
            name = display_name
            suffix = 2
            while name in taken:
                name = f"{display_name} ({suffix})"
                suffix += 1
            taken.add(name)
            IssueProperty.objects.create(
                workspace_id=issue_type.workspace_id,
                issue_type=issue_type,
                system_key=system_key,
                display_name=name,
                description=description,
                property_type="member",
                is_multi=is_multi,
                sort_order=sort_order,
            )


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0133_email_outbox_outer_subject"),
        ("ext", "0037_workshops_per_project"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="issueproperty",
            name="system_key",
            field=models.CharField(
                blank=True,
                choices=[
                    ("workshop_sales", "Workshop sales"),
                    ("workshop_pm", "Workshop project manager"),
                    ("workshop_trainer", "Workshop trainer"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name="issueproperty",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True), models.Q(("system_key", ""), _negated=True)),
                fields=("issue_type", "system_key"),
                name="ext_issue_property_unique_system_key_per_type",
            ),
        ),
        # Reversing drops the column with the properties in it, so there is
        # nothing to undo by hand.
        migrations.RunPython(provision_workshop_role_properties, migrations.RunPython.noop),
    ]
