# Generated by Django 4.2.30 on 2026-07-30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0127_issue_type_system_keys"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileasset",
            name="upload_validation_version",
            field=models.SmallIntegerField(default=0, editable=False),
        ),
    ]
