# Generated by Django 5.2.16 on 2026-09-02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("db", "0130_spend_invitations_already_honoured")]

    operations = [
        migrations.RemoveConstraint(model_name="issuetype", name="issue_type_system_key_invariants"),
        migrations.AlterField(
            model_name="issuetype",
            name="system_key",
            field=models.CharField(
                blank=True,
                choices=[("task", "Task"), ("epic", "Epic"), ("workshop", "Workshop")],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="issuetype",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(system_key__isnull=True)
                    | models.Q(system_key="epic", is_epic=True, is_active=True, is_default=False, level=1)
                    | models.Q(system_key="task", is_epic=False, is_active=True, is_default=True, level=0)
                    | models.Q(system_key="workshop", is_epic=False, is_active=True, is_default=False, level=0)
                ),
                name="issue_type_system_key_invariants",
            ),
        ),
    ]
