{{- if .Values.evaluation.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.evaluation.serviceAccountName }}
  labels:
    {{- include "hangar.labels" . | nindent 4 }}
    app.kubernetes.io/component: evaluation-dependencies
automountServiceAccountToken: false
{{- end }}
