apiVersion: v2
name: hangar
description: Secure Kubernetes deployment for Hangar
type: application
version: 0.1.0-rc.4
appVersion: v0.1.0-rc.4
kubeVersion: ">=1.30.0-0 <1.37.0-0"
home: https://github.com/szymczag/hangar
sources:
  - https://github.com/szymczag/hangar
maintainers:
  - name: Maciej Szymczak
annotations:
  artifacthub.io/license: AGPL-3.0-only
dependencies:
  - name: postgres
    alias: evaluation-postgresql
    version: 1.6.4
    repository: https://groundhog2k.github.io/helm-charts/
    condition: evaluation.enabled
  - name: rabbitmq
    alias: evaluation-rabbitmq
    version: 2.3.2
    repository: https://groundhog2k.github.io/helm-charts/
    condition: evaluation.enabled
  - name: valkey
    alias: evaluation-valkey
    version: 2.3.1
    repository: https://groundhog2k.github.io/helm-charts/
    condition: evaluation.enabled
